version: "3.3"

services:
    postgres:
        container_name: postgres
        image: postgres:latest
        ports:
        - "5432:5432"
        volumes:
        - /data/postgres:/data/postgres
        env_file:
            - docker.env
        networks:
            - postgres
    newapp:
        networks:
            - postgres
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"

networks:
    postgres:
        #driver: bridge
